### PR TITLE
Add autopay / 360 functionality

### PR DESCRIPTION
**Pull request by tallywiesenberg**
- Renames `_tellor` in constructor to "_oracle" as we don't use TellorMaster in 360 and L2s
- Adds `_autopay` to constructor, which creates an `ITellor` instance pointed at `autoPay`
- Add `setupDataFeed()` wrapper to `UsingTellor`

### CODE REVIEW

**Comment by tkernell** [comment]
These changes look good. The tests don't seem to run though, there are a few things missing from the `360audit` branch, and we should also update the playground and test these autopay additions to usingtellor. I can help work on these next week.

**Review by themandalore — APPROVED** [review]

**Comment by themandalore** [comment]
@tallywiesenberg , can you resolve conflicts?  Might have to repull and rebuild the artifacts

**Comment by tallywiesenberg** [comment]
@themandalore  @tkernell For this PR, I've added Autopay wrappers to UsingTellor, but this has led to a circular import, as Autopay uses UsingTellor, which takes Autopay has a constructor argument :(. I thought adding `setupDataFeed()` to UsingTellor would be useful for hackathons and UX, but it's not particularly urgent...thoughts? or is there a way to resolve this i'm missing :)

**Review by themandalore — APPROVED** [review]

**Comment by themandalore** [comment]
any reason why the tests fail @tallywiesenberg ?

**Comment by tallywiesenberg** [comment]
> any reason why the tests fail @tallywiesenberg ?

see the above, the tests fail because of a circular import

**Pull request merged**
