### PR TITLE
Bytes fix

### PR DESCRIPTION
**Pull request by themandalore**

### CODE REVIEW

**Comment by themandalore** [comment]
looked up the accepted way to convert bytes to uint and used this

**Comment by tkernell** [comment]
both _sliceUint versions seem to work with the shorter bytes, but abi.decode does not work

**Comment by themandalore** [comment]
> both _sliceUint versions seem to work with the shorter bytes, but abi.decode does not work

but why are the sliceUint's different?  is there a right way or is it just a different method.  

And yeah, abi.decode only works if the bytes are the right length (padded)

**Comment by tkernell** [comment]
these are just different methods. when you shift right one byte, everything to the left gets multiplied by 2^8. these are two methods for doing that multiplication: multiply each byte separately, or multiply all past bytes iteratively:
`a_0*b^2 + a_1*b + a_2 == ((a_0*b) + a_1)b + a_2`

**Comment by tkernell** [comment]
Updated here: https://github.com/tellor-io/usingtellor/pull/84 as per Damian's suggestion

**Pull request closed without merging**
