### PR TITLE
Fix all linting errors.

### PR DESCRIPTION
**Pull request by krasi-georgiev**
No functional changes

Just applied the auto formating and fixed all lint warnings.

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
@JGcarv since there are no actual functional changes I am merging it. If you think something doesn't look right ping me and will open another PR to fix. Thanks

**Comment by JGcarv** [comment]
I think it looks good. I'll just bump the npm version and publish it

**Comment by krasi-georgiev** [comment]
Why publishing it? I am usually just using `npm install tellor-io/usingtellor#....`

**Comment by JGcarv** [comment]
I think most people just do `npm install usingTellor`, so it's good to update on npm, I think

**Pull request merged**
