### PR TITLE
ci: created unit test github action.

### PR DESCRIPTION
**Pull request by zhyd1997**
Resolve: #89

### CODE REVIEW

**Comment by zhyd1997** [comment]
something was wrong: https://github.com/zhyd1997/usingtellor/actions/runs/3049900291/jobs/4916441401
Screen Shot 2022-09-14 at 11 21 25


don't know why but `npm test` works on the local machine:
Screen Shot 2022-09-14 at 11 21 47

**Review by themandalore — APPROVED** [review]

**Comment by themandalore** [comment]
thanks @zhyd1997 !

**Comment by themandalore** [comment]
looks like the unit test is now failing @zhyd1997 ...any chance you can fix it with a new pr or we'll just revert this one

**Comment by zhyd1997** [comment]
@themandalore Could you set a secret in the repo as `.env.example` file shows?

**Pull request merged**
